### ISSUE TITLE
How to add local users into database?

### ISSUE THREAD

**Issue by TaigoKuriyama** [DeNA/nota#8]
>No Local User management UI. We use SAML authentication, and local users have only beed used for development so no UI for user creation, password change, etc exists. It is possible to create local users directly into the database and login.

**Comment by jonatan-alama** [comment]
I am sorry there is no easy way right now.

There is some example for the default `admin/admin` user in the following file:
https://github.com/DeNA/nota/blob/main/packages/nota-server/migrations/00100-create-users.js#L69

The function that defines the password hash is in here:
https://github.com/DeNA/nota/blob/main/packages/nota-server/src/lib/authUtils.js#L4

**Comment by jonatan-alama** [comment]
@TaigoKuriyama We created an script to make local user creation easier. 

You can find how to use it in the README:
https://github.com/DeNA/nota#create-new-local-user--change-local-user-password

Please let us know if you have any problem.

**Comment by TaigoKuriyama** [comment]
I’ll give it a try. Thanks!
